language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache: pip
before_install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy scipy Cython coveralls nose-cov
script: nosetests --with-cov
after_success: coveralls
